obstacle_range: 2.5
raytrace_range: 3.0 #10.0
#footprint: [[0.30, 0.25], [0.30, -0.25], [-0.50, -0.25], [-0.50, 0.25]]
robot_radius: 0.26 #0.335 #0.18
# http://www.laas.fr/robots/rackham/data/en/robot.php
# Rackham is a B21r robot (iRobot). It is a 4-feet (118 cm) tall and 20-inches (52 cm) wide cylinder topped with a mast supporting a kind of helmet.
#robot_radius: ir_of_robot
inflation_radius: 1.0 #1.0
cost_scaling_factor: 10 #0.5
# exp(-1.0 * cost_scaling_factor * (distance_from_obstacle - inscribed_radius)) * (costmap_2d::INSCRIBED_INFLATED_OBSTACLE - 1), 
# where costmap_2d::INSCRIBED_INFLATED_OBSTACLE is currently 254. 
observation_sources: base_scan
base_scan: {
  sensor_frame: lrf_link, 
  topic: front/scan, #/base_scan,
  data_type: LaserScan, 
  expected_update_rate: 1.0,
  observation_persistence: 0.0, 
  marking: true, 
  clearing: true, 
  max_obstacle_height: 1.0, 
  min_obstacle_height: -0.15
  }  

transform_tolerance: 1.5
  
